name: Update stat cards

on:
  # run on every push to main branch
  push:
    branches:
      - main

  # run automatically once every day
  schedule:
    - cron: "0 0 * * *"

  # allows to run job manually
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=${{ github.repository_owner }}&theme=calm&show_icons=true&hide_title=true&count_private=true&include_all_commits=true&role=OWNER,ORGANIZATION_MEMBER,COLLABORATOR&rank_icon=github&show=prs_reviewed,prs_merged_percentage
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top langs card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=${{ github.repository_owner }}&hide_title=true&hide_border=true&layout=compact&langs_count=10&hide=makefile,html,css,jupyter%20notebook&text_color=fff&icon_color=fff&bg_color=000
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      # push the content of <profile_dir> to a branch
      # content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> as a github page
      - name: Commit cards
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: stats
          build_dir: profile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
